version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php
    # image: edipoelwes/php-7.4
    container_name: "${APP_CONTAINER_NAME}"
    restart: always
    tty: true
    environment:
      SERVICE_NAME: "${APP_SERVICE_NAME}"
      SERVICE_TAGS: dev
    working_dir: "${APP_WORKING_DIR}"
    volumes:
      - ./:/var/www
      # - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ${NETWORK}
    
  webserver:
    image: nginx:alpine
    container_name: "${WEBSERVER_CONTAINER_NAME}"
    restart: always
    tty: true
    ports:
      - "${WEBSERVER_PORT}:80"
     # - "443:443"
    volumes:
      - ./:/var/www
      - ./:/etc/nginx/conf.d/
    networks:
      - ${NETWORK}

  # s3:
  #   image: minio/minio:latest
  #   ports:
  #     - "9000:9000"
  #     - "9099:9099"
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   volumes:
  #     - ./storage-minio:/data
  #   command: server --address ":9099" --console-address ":9000" /data
  #   restart: always # necessary since it's failing to start sometimes
  #   networks:
  #     - ${NETWORK}


#Docker Networks
networks:
  siafc:
    driver: bridge
