version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php
    # image: edipoelwes/php-7.4
    container_name: "app"
    restart: always
    tty: true
    environment:
      SERVICE_NAME: "${APP_SERVICE_NAME}"
      SERVICE_TAGS: dev
    working_dir: "${APP_WORKING_DIR}"
    volumes:
      - ./:/var/www
      # - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ${NETWORK}
    
  siafc:
    image: nginx:alpine
    container_name: "siafc"
    restart: always
    tty: true
    ports:
      - "82:80"
     # - "443:443"
    volumes:
      - ./:/var/www
      - ./config/siafc:/etc/nginx/conf.d/
    networks:
      - ${NETWORK}

  # centralcontribuinte:
  #   image: nginx:alpine
  #   container_name: "central_do_contribuinte"
  #   restart: always
  #   tty: true
  #   ports:
  #     - "83:80"
  #    # - "443:443"
  #   volumes:
  #     - ./:/var/www
  #     - ./config/centraldocontribuinte:/etc/nginx/conf.d/
  #   networks:
  #     - ${NETWORK}
  
  db_postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    tty: true
    working_dir: /var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jaicos
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # - /Users/edipoelwes/Documents/sts/siafc/db:/var/lib/postgresql
      - ./db:/var/lib/postgresql/data
      - ./dump:/var/lib/postgresql/dump
      # - ./dump:/docker-entrypoint-initdb.d
    networks:
      - ${NETWORK}

#Docker Networks
networks:
  siafc:
    driver: bridge
